# Generated by Django 5.1.2 on 2024-11-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img.jpg', upload_to='main/static/main/img', verbose_name='Изооброжения'),
            preserve_default=False,
        ),
    ]
