# Generated by Django 5.1.2 on 2024-11-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='image/%Y ', verbose_name='Изооброжения'),
        ),
    ]
