# Generated by Django 5.1.2 on 2024-11-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_img_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='text_coments',
        ),
        migrations.AddField(
            model_name='comments',
            name='text_comments',
            field=models.TextField(default=1, max_length=2000, verbose_name='Текст коментария'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя пользователя'),
        ),
    ]
